name: tests

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    # Make Laravel use a throwaway sqlite DB and in-memory drivers
    env:
      APP_ENV: testing
      APP_KEY: base64:AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
      CACHE_DRIVER: array
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: array
      LOG_CHANNEL: stack
      DB_CONNECTION: sqlite
      DB_DATABASE: database/database.sqlite

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          cp .env.example .env
          php -r "file_exists('database') || mkdir('database');"
          php -r "file_exists('database/database.sqlite') || touch('database/database.sqlite');"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer:v2

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Node deps
        run: npm ci --no-audit --no-fund || npm i --no-audit --no-fund

      - name: Build (optional)
        run: npm run build --if-present

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations (sqlite)
        run: php artisan migrate --force

      - name: PHP Unit tests
        run: php artisan test -q
